apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: myevent-subscription
#  namespace: climeworks-rabbitmq
spec:
  pubsubname: pubsub-rabbitmq-topic-sql
  topic: sql
  routes:
    default: /process
scopes:
  - dapr2sql
